export type PillIconName
  = | 'pause'
    | 'resume'
    | 'assert'
    | 'hover'
    | 'stop'
    | 'exists'
    | 'visible'
    | 'hidden'
    | 'checked'
    | 'disabled'
    | 'text'
    | 'value'
    | 'contains'
    | 'url'
